Cleanup logic around recommended and filters

diff --git a/scripts/nord_connect b/scripts/nord_connect
--- a/scripts/nord_connect
+++ b/scripts/nord_connect
@@ -3,23 +3,28 @@ shopt -s nocasematch
 
 [[ -n ${PRE_CONNECT} ]] && eval ${PRE_CONNECT}
 
-## Get RECOMMENDED if internet accessible
-if [[ $(curl -s --connect-timeout 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
+SERVER=$1
+if [[ -z ${SERVER} ]]
 then
-  RECOMMENDED=$1
-  [[ -z ${RECOMMENDED} ]] && RECOMMENDED=$(nord_recommend)
-  SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
-
-  ## Determine is valid servername
-  if [[ -z ${SERVER} || ${SERVER} == "null" ]]
+  ## Get RECOMMENDED if internet accessible
+  if [[ $(curl -s --connect-timeout 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
   then
-    if [[ -n ${CONNECTION_FILTERS} ]]
+    ## Obtain recommended server from API
+    RECOMMENDED=$(nord_recommend)
+    SERVER=$(echo ${RECOMMENDED} | jq --raw-output .servername)
+
+    ## Determine is valid servername
+    if [[ -z ${SERVER} || ${SERVER} == "null" ]]
     then
-      echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; retrying without filters"
-    else
-      echo -e $(date "+%F %T%z") "\tWARNING\tCannot connect to recommended; retrying with default"
+      if [[ -n ${CONNECTION_FILTERS} ]]
+      then
+        echo -e "WARNING\tInvalid connection string; retrying without filters"
+      else
+        echo -e "WARNING\tCannot connect to recommended; retrying with default"
+      fi
+      ## Let NordVPN client select the server
+      unset SERVER
     fi
-    unset SERVER
   else
     echo "The recommended server is ${SERVER}"
   fi
@@ -31,16 +36,14 @@ until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
 do
   if [ ${current_sleep} -gt 32 ]
   then
-    echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
-    exit 2
+    echo -e "CRITICAL\tUnable to connect; exiting"
+    exit 1
   fi
-  echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
+  echo -e "WARNING\tUnable to connect; retrying in ${current_sleep} seconds."
   sleep ${current_sleep}
   current_sleep=$((current_sleep * 2))
 done
 
 [[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}
 
-## Clear recommended
-unset RECOMMENDED
 exit 0
diff --git a/scripts/nord_watch b/scripts/nord_watch
--- a/scripts/nord_watch
+++ b/scripts/nord_watch
@@ -50,25 +50,33 @@ do
   then
     if [ $tDATE -le $nDATE ]
     then
-      ## Reconnect
-      echo -e $(date "+%F %T%z") "\tINFO\tTarget reconnect time reached; reconnecting"
-      echo "########################"
-      RECOMMENDED=$(nord_recommend)
+      echo -e $(date "+%F %T%z") "\tINFO\tTarget reconnect time reached; assess connection"
+      ## Determine recommended server from API
+      RECOMMENDED=$(nord_recommend ${CONNECTION_FILTERS})
       ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
-      if [ ${ACTION} != "stay" ]
+      HOST=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
+      SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
+      if [ ${ACTION} == "stay" ]
       then
+        if [ ${HOST} == "null" ]
+        then
+          echo -e $(date "+%F %T%z") "\tWARNING\tCannot determine recommended server; retaining current connection"
+        else
+          echo -e $(date "+%F %T%z") "\tINFO\tAlready connected to the recommended server ($HOST); retaining current connection"
+        fi
+      else
+        ## Reconnect
+        echo "########################"
+        echo "The recommended server is ${SERVER}; reconnecting"
         nordvpn disconnect | grep -Ei -f /opt/reg-grep
-        if ! nord_connect ${RECOMMENDED}
+        if ! nord_connect ${SERVER}
         then
           echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
           CODE=2
           break
         fi
-      else
-        host=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
-        echo "You are already connected to the recommended server ($host)"
+        echo "########################"
       fi
-    echo "########################"
     ## Reset reconnection target
     Set-Target ${RECONNECT_INTERVAL}
     fi
