Refine error handling

diff --git a/scripts/nord_connect b/scripts/nord_connect
--- a/scripts/nord_connect
+++ b/scripts/nord_connect
@@ -5,7 +5,11 @@
 current_sleep=1
 RECOMMENDED=$(nord_recommend)
 SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
-[[ -n ${SERVER} ]] || echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; exiting" && exit 1
+if [[ -z ${SERVER} ]]
+then
+  echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; exiting"
+  exit 1
+fi
 ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
 if [[ ${ACTION} != "stay" ]]
   then
