Refactor use of recommended

diff --git a/scripts/nord_connect b/scripts/nord_connect
--- a/scripts/nord_connect
+++ b/scripts/nord_connect
@@ -3,9 +3,18 @@ shopt -s nocasematch
 
 [[ -n ${PRE_CONNECT} ]] && eval ${PRE_CONNECT}
 
-current_sleep=1
-RECOMMENDED=$(nord_recommend)
+RECOMMENDED=$1
+if [[ -z ${RECOMMENDED} ]]
+## Get RECOMMENDED if internet accessible
+then
+  if [[ $(curl -s --connect-timeout 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
+  then
+    RECOMMENDED=$(nord_recommend)
+  fi
+fi
 SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
+
+## Determine is valid servername
 if [[ -z ${SERVER} || ${SERVER} == "null" ]]
 then
   if [[ -n ${CONNECTION_FILTERS} ]]
@@ -14,29 +23,27 @@ then
   else
     echo -e $(date "+%F %T%z") "\tWARNING\tCannot connect to recommended; retrying with default"
   fi
-  SERVER=""
-  ACTION="go"
+  unset SERVER
 else
   echo "The recommended server is ${SERVER}"
-  ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
 fi
-if [[ ${ACTION} != "stay" ]]
-  then
-  until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
-  do
-    if [ ${current_sleep} -gt 32 ]
-    then
-      echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
-      exit 2
-    fi
-    echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
-    sleep ${current_sleep}
-    current_sleep=$((current_sleep * 2))
-  done
 
-  [[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}
-else
-  host=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
-  echo "You are already connected to the recommended server ($host)"
-fi
+## Make the connection
+current_sleep=1
+until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
+do
+  if [ ${current_sleep} -gt 32 ]
+  then
+    echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
+    exit 2
+  fi
+  echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
+  sleep ${current_sleep}
+  current_sleep=$((current_sleep * 2))
+done
+
+[[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}
+
+## Clear recommended
+unset RECOMMENDED
 exit 0
diff --git a/scripts/nord_watch b/scripts/nord_watch
--- a/scripts/nord_watch
+++ b/scripts/nord_watch
@@ -50,17 +50,24 @@ do
       ## Reconnect
       echo -e $(date "+%F %T%z") "\tINFO\tTarget reconnect time reached; reconnecting"
       echo "########################"
-      nordvpn disconnect | grep -Ei -f /opt/reg-grep
-      if ! nord_connect
+      RECOMMENDED=$(nord_recommend)
+      ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
+      if [ ${ACTION} != "stay"]
       then
-        echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; exiting"
-        CODE=2
-        break
-      fi
-      echo "########################"
-      ## Reset reconnection target
-      Set-Target ${RECONNECT_INTERVAL}
-      fi
+        nordvpn disconnect | grep -Ei -f /opt/reg-grep
+        if ! nord_connect ${RECOMMENDED}
+        then
+          echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; exiting"
+          CODE=2
+          break
+        fi
+      else
+        host=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
+        echo "You are already connected to the recommended server ($host)"
+    fi
+    echo "########################"
+    ## Reset reconnection target
+    Set-Target ${RECONNECT_INTERVAL}
   fi
 done
 exit ${CODE:-3}
