Update to include recommended from 26c8225f80

diff --git a/scripts/nord_connect b/scripts/nord_connect
--- a/scripts/nord_connect
+++ b/scripts/nord_connect
@@ -1,14 +1,38 @@
 #!/bin/bash
+shopt -s nocasematch
 
 [[ -n ${PRE_CONNECT} ]] && eval ${PRE_CONNECT}
 
+## Get RECOMMENDED if internet accessible
+if [[ $(curl -s --connect-timeout 5 "${CHECK_CONNECTION_URL:-https://www.google.com}") ]]
+then
+  RECOMMENDED=$1
+  [[ -z ${RECOMMENDED} ]] && RECOMMENDED=$(nord_recommend)
+  SERVER=$(echo $RECOMMENDED | jq --raw-output .servername)
+
+  ## Determine is valid servername
+  if [[ -z ${SERVER} || ${SERVER} == "null" ]]
+  then
+    if [[ -n ${CONNECTION_FILTERS} ]]
+    then
+      echo -e $(date "+%F %T%z") "\tWARNING\tInvalid connection string; retrying without filters"
+    else
+      echo -e $(date "+%F %T%z") "\tWARNING\tCannot connect to recommended; retrying with default"
+    fi
+    unset SERVER
+  else
+    echo "The recommended server is ${SERVER}"
+  fi
+fi
+
+## Make the connection
 current_sleep=1
-until nordvpn connect ${CONNECT} | grep -Ei -f /opt/reg-grep
+until nordvpn connect ${SERVER} | grep -Ei -f /opt/reg-grep
 do
   if [ ${current_sleep} -gt 32 ]
   then
-    echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect."
-    exit 1
+    echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
+    exit 2
   fi
   echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; retrying in ${current_sleep} seconds."
   sleep ${current_sleep}
@@ -17,4 +41,6 @@ done
 
 [[ -n ${POST_CONNECT} ]] && eval ${POST_CONNECT}
 
+## Clear recommended
+unset RECOMMENDED
 exit 0
diff --git a/scripts/nord_watch b/scripts/nord_watch
--- a/scripts/nord_watch
+++ b/scripts/nord_watch
@@ -1,7 +1,6 @@
 #!/bin/bash
 
-## Establish reconnection target in minutes
-RECONNECT_INTERVAL=${REFRESH_CONNECTION_INTERVAL:-120}
+## Function to set reconnect time
 function Set-Target {
   ## Current time
   sDATE=$(date "+%H%M")
@@ -11,6 +10,10 @@ function Set-Target {
   tDATE=$(date "+%Y%m%d%H%M" --date="$eDATE")
   echo -e $(date "+%F %T%z") "\tINFO\tTarget reconnect time is '$eDATE'"
 }
+
+## Establish reconnection target in minutes
+RECONNECT_INTERVAL=${REFRESH_CONNECTION_INTERVAL:-120}
+
 ## Determine if periodic reconnection is enabled
 if [ $RECONNECT_INTERVAL -ne 0 ]
 then
@@ -35,7 +38,7 @@ do
     nordvpn status | grep -Eiv -f /opt/inv-grep
     if ! nord_connect
     then
-      echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; exiting"
+      echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
       CODE=1
       break
     fi
@@ -50,17 +53,25 @@ do
       ## Reconnect
       echo -e $(date "+%F %T%z") "\tINFO\tTarget reconnect time reached; reconnecting"
       echo "########################"
-      nordvpn disconnect | grep -Ei -f /opt/reg-grep
-      if ! nord_connect
+      RECOMMENDED=$(nord_recommend)
+      ACTION=$(echo $RECOMMENDED | jq --raw-output .action)
+      if [ ${ACTION} != "stay" ]
       then
-        echo -e $(date "+%F %T%z") "\tWARNING\tUnable to connect; exiting"
-        CODE=2
-        break
+        nordvpn disconnect | grep -Ei -f /opt/reg-grep
+        if ! nord_connect ${RECOMMENDED}
+        then
+          echo -e $(date "+%F %T%z") "\tCRITICAL\tUnable to connect; exiting"
+          CODE=2
+          break
+        fi
+      else
+        host=$(echo ${RECOMMENDED} | jq --raw-output .hostname)
+        echo "You are already connected to the recommended server ($host)"
       fi
-      echo "########################"
-      ## Reset reconnection target
-      Set-Target ${RECONNECT_INTERVAL}
-      fi
+    echo "########################"
+    ## Reset reconnection target
+    Set-Target ${RECONNECT_INTERVAL}
+    fi
   fi
 done
 exit ${CODE:-3}
